[package]
name = "dragonet"
version = "0.0.0"
edition = "2021"
description = "A protocol framework that automatically generates networking code."
license = "Apache-2.0"

[dependencies]
mio = { version = "1.0.2", features = ["net", "os-poll"]}
dragonet-macros = { path = "../dragonet-macros" }