[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"
license = "Apache-2.0"

[dev-dependencies]
dragonet = { path = "../dragonet" }


[[example]]
name = "echo"
path = "echo.rs"